Move config file to a metrics-owned directory.
We suspect the config file needs to be in a directory that the metrics
user can write to. Before it was /etc, which is only writable by root.
Now it is in /etc/metrics, which the eos-metrics.conf file ensures is
writable by and owned by the metrics user.

[endlessm/eos-sdk#1573]

diff --git a/tools/eos-select-metrics-env.in b/tools/eos-select-metrics-env.in
--- a/tools/eos-select-metrics-env.in
+++ b/tools/eos-select-metrics-env.in
@@ -1,14 +1,13 @@
 #!/bin/bash -e
-CONFIG_FILE=@sysconfdir@/eos-metrics-permissions.conf
 
-if [ ! -f $CONFIG_FILE ]; then
-    echo "Configuration file at @sysconfdir@/eos-metrics-permissions.conf not found." >&2
+if [ ! -f @permissions_file@ ]; then
+    echo "Configuration file at @permissions_file@ not found." >&2
     exit 1
 fi
 
 ENVIRONMENT=$1
 if [ "$ENVIRONMENT" == "dev" ] || [ "$ENVIRONMENT" == "test" ] || [ "$ENVIRONMENT" == "production" ]; then
-    sed -i "s/\(environment *= *\).*/\1$ENVIRONMENT/" $CONFIG_FILE
+    sed -i "s/\(environment *= *\).*/\1$ENVIRONMENT/" @permissions_file@
 else
     echo "Invalid enviroment $ENVIRONMENT passed in as parameter." >$2
     exit 2
